public with sharing class ConstantUtility {
    public static String CONFIG_DATA_RET_ERR = 'An error occurred while retrieving Config data.';
    public static String CASECONFIG_DATA_RET_ERR = 'An error occurred while retrieving Case Config data.';
    public static String CASECONFIG_DATA_ADD_ERR = 'Failed to add new Case Config records. Error: ';
    public static String CALLOUT_FAILED_ERR = 'Callout Failed. Response code: ';
    public static String CASECONFIG_DATA_SEND_ERR = 'Failed to perform action on Case Config records. Error: ';
    public static String FAILED = 'Failed';
    public static String CLOSED = 'Closed';
}